FROM php:8-apache

ARG USER_NAME=app
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID -o $USER_NAME && \
    useradd -m -u $UID -g $GID $USER_NAME

RUN apt-get update && \
    apt-get install -y \
        unzip \
        nodejs \
        npm

COPY docker/app/resources/php/composer.phar /usr/bin/composer

# ------------------------------------------------------------------------------
# install the app
# ------------------------------------------------------------------------------
COPY app /var/www/html/photo_frame
WORKDIR /var/www/html/photo_frame
RUN composer install && \
    npm install && \
    npm prod

# ------------------------------------------------------------------------------
# configure apache
# ------------------------------------------------------------------------------

RUN a2dissite 000-default
COPY docker/app/resources/apache/ports.conf /etc/apache2/ports.conf
COPY docker/app/resources/apache/site.conf /etc/apache2/sites-enabled/site.conf

USER $USER_NAME
