FROM alpine AS qemu

#QEMU Download
ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM arm32v7/php:8-apache
# Add QEMU
COPY --from=qemu qemu-arm-static /usr/bin

ARG USER_NAME=app
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID -o $USER_NAME && \
    useradd -m -u $UID -g $GID $USER_NAME

RUN apt-get update && \
    apt-get install -y \
        unzip \
        nodejs \
        npm

COPY docker/app/resources/php/composer.phar /usr/bin/composer


# ------------------------------------------------------------------------------
# install the app
# ------------------------------------------------------------------------------
COPY app /var/www/html/photo_frame
WORKDIR /var/www/html/photo_frame
RUN composer install && \
    npm install && \
    npm run prod

# ------------------------------------------------------------------------------
# configure apache
# ------------------------------------------------------------------------------
RUN a2dissite 000-default
COPY docker/app/resources/apache/ports.conf /etc/apache2/ports.conf
COPY docker/app/resources/apache/site.conf /etc/apache2/sites-enabled/site.conf

USER $USER_NAME
